### ISSUE TITLE
Three "Bib record without UT but..." reports need to have upper and lower limits removed

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#102]
_Bib record without UT but title contains transl_ (Local Cat Maint > Bibliographic Records: Titles)
_Bib record without UT but 700 field contains tr_ (Local Cat Maint > Bibliographic Records: Titles)
_Bib record without UT but 6xx field contains Translations into_ (Local Cat Maint > Bibliographic Records: Titles)

@gibsonjc stated: These three similar reports all work and return the same results as Access [because the database I was testing with had fewer than 3000000 records in it], however, one of them (_Bib record without UT but title contains transl_) prompts for starting and ending bib number while the other two [_Bib record without UT but 700 field contains tr_ and _Bib record without UT but 6xx field contains Translations into_] do not because they appear to have hardcoded numbers of **WHERE ((BIB_TEXT.BIB_ID Between 300 AND 3000000** in the SQL. I'm not sure why these queries on our Shared SQL page had prompts for beginning and ending bibs anyway. Can you rewrite all three of these to find all matching records without prompting for start and end bib IDs?

@csaundrs asked: On the 3 that have bib_id ranges, should I take out that condition altogether or should I hard code the upper and lower limits to certain values?

@gibsonjc answered: Since we have databases of varying sizes, I think it would be simplest if you can take out the condition altogether so that any library running this report will find all of the matching bibs in their entire database. Unless you see something that makes this a bad idea for performance or unreasonable results times, of course!

This was split out from Issue #94

**Comment by csaundrs** [comment]
It's been a while since I looked at this one.  I guess I forgot....   But the 3 reports have had their parameters removed (range defined by upper and lower bib_id limit) on devel.  They are ready for inspection and if they are ok, to be moved to production.


It's worth noting that:
Bib record without UT but title contains transl (Local Cat Maint > Bibliographic Records: Titles)

Returned many, many rows when I tested against the KNX database, so I'm not sure it is truly an exceptional condition....or that there is something amiss with the records found....but then I'm not sure what the implications of the criteria really are as they relate to bib records...

**Comment by gibsonjc** [comment]
The results match the same queries in Access, so I think that these are working properly. 

Still to be done: run in UIU

**Comment by gibsonjc** [comment]
Done in UIU.  "Bib record without UT but 6xx field contains Translations into" took 7 minutes; the other two reports took 2 minutes.

**Comment by patrickzurek** [comment]
All three reports moved to prod.  They ran fine there.
