### ISSUE TITLE
Several reports are ready for testing

### ISSUE THREAD

**Issue by csaundrs** [CARLI/web-reports#137]
These reports can be tested and ( if they look good ) moved to production web-reports:

1) Description of a Library's Collection - General - Bib records of a specific format in a particular location
2) Cataloging Activity and Statistics - Bib Records Updated By Operator
3) Local Catalog Maintenance - Bibliographic Records - Fixed Fields - Bib records with 008 DATE1 less than 4 chars
4) Local Catalog Maintenance - Bibliographic Records - Fixed Fields - Bib records with 008 DATE1 may contain invalid “u” data
5) Local Catalog Maintenance - Bibliographic Records - Fixed Fields - Bib records with 008 DATE2 less than 4 chars
6) Local Catalog Maintenance - Bibliographic Records - Fixed Fields - Bib records with Lang code set to obsolete or invalid value
7) Local Catalog Maintenance - Bibliographic Records - General - Bib records with null 260c, for scores and sound recordings only
8) Description of a Library's Collection - General - Bib records with particular subj heading strings dedup 
9) Local Catalog Maintenance - Bibliographic Records - Control Numbers - Bibliographic record 010 $a contains ocm may be OCLC number
10) Local Catalog Maintenance - Bibliographic Records - Control Numbers - Bibliographic record 010 $a contains pbk may be ISBN
11) Local Catalog Maintenance - Bibliographic Records - Control Numbers - Bibliographic record 020 $a contains double slash may be LCCN
12) Local Catalog Maintenance - Bibliographic Records - Control Numbers - Bibliographic record 020 $a contains ocm may be OCLC number
13) Local Catalog Maintenance - Bibliographic Records - Control Numbers - Bibliographic record 022 $a not 8 digits
14) Local Catalog Maintenance - Bibliographic Records - Control Numbers - Bibliographic record 035 $a contains DRA bib ID
15) Local Catalog Maintenance - Bibliographic Records - Control Numbers - Bibliographic record 035 $a contains hyphen may be LCCN
16) Local Catalog Maintenance - Bibliographic Records - Control Numbers - Bibliographic record 035 $a contains punctuation may be barcode
17) Local Catalog Maintenance - Bibliographic Records - Fixed Fields - Bibliographic records where 008 DATE1 does not equal 260c

**Comment by csaundrs** [comment]
I have added some more:

18. Local Catalog Maintenance - Bibliographic Records - General - Bibliographic records with 260c beginning with letter EL
19. Local Catalog Maintenance - Bibliographic Records - General - Bibliographic records with 260c containing the letter EL
20. Local Catalog Maintenance - Bibliographic Records - Fixed Fields - Bibliographic Records with invalid or obsolete format coding
21. Local Circulation Statistics - Other Circ Activity Statistics - Circulation Transactions by Library of Congress Classification

**Comment by gibsonjc** [comment]
Moved 18-21 to Issue #138  :)

**Comment by gibsonjc** [comment]
@patrickzurek At your convenience, 15 of these 17 reports can be moved to PRODUCTION web-reports:

1 - Description of a Library's Collection > General > Bib records of a specific format in a particular location  

This one is special, however, because it is the one I had to re-enter from scratch to add a new Parameter for the supporting query.  The new one is **bib_records_of_a_specific_format_in_a_particular_location2.report** and that's the one we want on production.  

I tried to delete bib_records_of_a_specific_format_in_a_particular_location.report (without the 2 on the end) but it caused all of my Results to stop displaying.  If you can find a safe way to rename the new and remove the original, please feel free!

2 - Cataloging Activity and Statistics > Bib Records Updated By Operator

3 - Local Catalog Maintenance > Bibliographic Records > Fixed Fields > Bib records with 008 DATE1 less than 4 chars

**NOT 4 - Issue** #139 (Bib records with 008 DATE1 may contain invalid "u" data)

5 - Local Catalog Maintenance > Bibliographic Records > Fixed Fields > Bib records with 008 DATE2 less than 4 chars

6 - Local Catalog Maintenance > Bibliographic Records > Fixed Fields > Bib records with Lang code set to obsolete or invalid value

7 - Local Catalog Maintenance > Bibliographic Records > General > Bib records with null 260c, for scores and sound recordings only

**NOT 8 - Issue** #140 (Bib records with particular subj heading strings dedup)

9 - Local Catalog Maintenance > Bibliographic Records > Control Numbers > Bibliographic record 010 $a contains ocm may be OCLC number

10 - Local Catalog Maintenance > Bibliographic Records > Control Numbers > Bibliographic record 010 $a contains pbk may be ISBN

11-  Local Catalog Maintenance > Bibliographic Records > Control Numbers > Bibliographic record 020 $a contains double slash may be LCCN

12 - Local Catalog Maintenance > Bibliographic Records > Control Numbers > Bibliographic record 020 $a contains ocm may be OCLC number

13 - Local Catalog Maintenance > Bibliographic Records > Control Numbers > Bibliographic record 022 $a not 8 digits

14 - Local Catalog Maintenance > Bibliographic Records > Control Numbers > Bibliographic record 035 $a contains DRA bib ID

15 - Local Catalog Maintenance > Bibliographic Records > Control Numbers > Bibliographic record 035 $a contains hyphen may be LCCN

16 - Local Catalog Maintenance > Bibliographic Records > Control Numbers > Bibliographic record 035 $a contains punctuation may be barcode

17 - Local Catalog Maintenance > Bibliographic Records > Fixed Fields > Bibliographic records where 008 DATE1 does not equal 260c

**Comment by patrickzurek** [comment]
Done.
