### ISSUE TITLE
new reports, OC6K and OC6L

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#147]
2 new reports: [moved from Issue #142]
1. Bib Record 035$a begins OCoLCon but has less than 10 digits (OC6.K)
2. Bib Record 035$a begins OCoLCocn but has more than 9 digits (OC6.L)

I've updated the shared Google spreadsheet list, uploaded his text file with the sql on files.carli.illinois.edu:/home/fellows/stat_sql, and will also attach it here for convenience. 
[OC6_sql_revisions_2018_tcs.txt](https://github.com/CARLI/web-reports/files/1612933/OC6_sql_revisions_2018_tcs.txt)

**Comment by jenhm** [comment]
For both queries if no results are found I receive the AJAX errorDataTables warning: table id=d-tables - Ajax error. For more information about this error, please see http://datatables.net/tn/7"

**Comment by jenhm** [comment]
2. Bib Record 035$a begins OCoLCocn but has more than 9 digits (OC6.L) 

This query is fine, and the results display correctly and as anticipated, unless there are not results and then I get the AJAX error as referenced above.

**Comment by jenhm** [comment]
1. Bib Record 035$a begins OCoLCon but has less than 10 digits (OC6.K) 
Even on RESdb there are no results (and the AJAX error) for this query. It may be the data are too old to have any of these, since the 10 digit number is the newest OCLC number combination. 

I tested on UIU, UIC, DPU on Devel with no hits. 

I checked on UIU on prod and got 1 result. 

BIB_ID | TITLE_BRIEF | OCLCNumDigits | DISPLAY_HEADING | NORMAL_HEADING | SUPPRESS_IN_OPAC | CREATE_DATE
-- | -- | -- | -- | -- | -- | --
8363202 | Reformation, Gesellschaft, Herrschaft : Sozialgeschichte der Reformationszeit im Duisburger und MuÌˆlheimer Raum / | 9 | (OCoLC)on989896555 | OCOLC 989896555 | N | 8/3/2017 8:00:40 PM

**Comment by jenhm** [comment]
Tested Bib Record 035$a begins OCoLCon but has less than 10 digits (OC6.K) by adding a bib to DPU on devel with the OCLC Number found in the example I got from Prod. The query worked as expected.

See issue #93 for the AJAX warning issue -- tested queries on Prod in Web-reports with no results do not give AJAX error so suspect it is just on devel.

**Comment by gibsonjc** [comment]
In production
