### ISSUE TITLE
Decide on number of recent reports to show in right side bar

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/web-reports#16]
There's a configurable option to limit the number of recent reports to display on the right side bar.  It's currently set to show the most recent 5.  Is this reasonable or does it need to be adjusted?

**Comment by gibsonjc** [comment]
This appears to be set at 7 now, not 5.  Seven seems like a fine amount to start with

I notice that when the left side bar is open, it does push everything to the right and that makes the list of recently run reports narrower, too. Ultimately, I would hate to make the main screen scroll just because the list of recently run queries was too long vertically.
