### ISSUE TITLE
Add ability to search for a report by keyword or title

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/web-reports#29]
Add some kind of search function to the list of Reports available to be run so that you could enter keywords to find reports with certain words in their titles.  Useful for someone who may have trouble finding the one they're looking for.

**Comment by gibsonjc** [comment]
If/when this searching is available, a good feature to have would be the ability to clear the search box.  (Previously known as: Can "x" be added to the search function of report output to clear it?)

(I am going to close #27 now because they are out of order.)

**Comment by PatrickZurekUIC** [comment]
This is in on devel.  There isn't an x to erase the search box because it's a little hard to implement with the way we have things set up now.

**Comment by patrickzurek** [comment]
This is in on devel. There isn't an x to erase the search box because it's a little hard to implement with the way we have things set up now.

**Comment by patrickzurek** [comment]
I forgot to mention that when you pull up a report template by clicking on a search result, the path to the report is displayed beneath the report name.  I did this because I felt that users, once having searched for a report, might desire to know how to get back to that report again in the future without having to search for it.  The path is only displayed for reports that have been arrived at via searching.

<img width="975" alt="screen shot 2016-06-08 at 8 38 09 am" src="https://cloud.githubusercontent.com/assets/6615138/15896119/791fcb96-2d54-11e6-9aca-aba75ee9c7fc.png">

**Comment by gibsonjc** [comment]
Good things: 
The searching within/for report title seems to work properly and well.  I like that it does real-time searching as you type like the HTML results do.  I do like the path to the report location being displayed beneath the name when you get to it via a search, that's a great feature you thought of!

Suggestions:

A) I think the heading for the results panel on the left should say "Matching Report Names" or something to be specific about what these are.  (I'm trying to avoid using the word "result" again since we already have some confusion about the multiple uses of the word (see #77 ).)  Even better yet, and maybe a bit dreamy, could the heading say something like: 
Report Names Matching 
"string you searched for"
That would be absolutely clear what these are, especially since the search box and the results are on opposite sides of the page.

B) One thing I don't like so much is that after doing a search, you are stuck with the "Search Results" side panel until you click the Reports link from the top to do a manual browse again.  (My first inclination was to click the x to close it and maybe the list of Reports would be underneath it even though I knew that was not likely to be true.)  I was hoping that the function might behave entirely like the Search box for the HTML results so that if I manually cleared the text in the search box (similar to if there were an x I could click in the box to clear it all at once), it would remove the results entirely. I realize it might not be possible for the system to remember what was in that sidebar area before I did a search, but maybe it would go back to a default screen of some kind...or maybe the side bar would disappear altogether so it looks like it does when you first log in and your see the splash screen with the instructions?  What do you think?

**Comment by patrickzurek** [comment]
I changed the headers to "Matching Report Names:" and "No Report Names Matching: ".

Under _that_ heading, I displayed in italics what the user was searching for.  

Closing the search box when a category was previously open reverts to that category.  If no category was open, the side bar closes.

**Comment by patrickzurek** [comment]
Also, it was pushed to prod.
