### ISSUE TITLE
Fund Transactions-All could use prepopulated boxes

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#34]
Fund Transactions-All could use prepopulated boxes for the two inputs, Ledger Name and Fiscal Period.

The MSAccess SQL for these is:

SELECT LEDGER.LEDGER_NAME
FROM LEDGER;

and 

SELECT FISCAL_PERIOD.FISCAL_PERIOD_NAME
FROM FISCAL_PERIOD;

**Comment by gibsonjc** [comment]
Note: the "real" **Fund Transactions - All** is under Acquisitions > Funds and Ledgers > FUND TRANSACTIONS – ALL

**Comment by patrickzurek** [comment]
I tried dogfooding this and using the web admin interface to make the change.  It revealed two problems.  The first was a problem in the javascript which I fixed.  The second is related to editing an existing report but changing it from a regular parameter to a pre-populated parameter.  I'll open a separate issue for bug #2, but for now, the workaround is when editing a report, don't change an existing parameter to a pre-populated one.  Just delete it and create a new parameter.

Jessica, I'd ask you to run a report and see if the parameters are in sync, but you have no way of looking at the output since it contains too many columns to display in HTML.  I'll work on CSV now.

**Comment by patrickzurek** [comment]
I added CSV to devel.  Take a look.  Also, don't forget to see my request in the previous comment about making sure the parameters are in sync with each other.

**Comment by gibsonjc** [comment]
Can you clarify what "see if the parameters are in sync" means?  :)

I believe I have successfully run the report and the output looks appropriate, though I haven't checked it against Access results yet.

One thing I notice is that the options in the two drop down parameter menus (FISCAL PERIOD and LEDGER NAME) don't appear to be displaying in any particular order.  Not alphabetical or numeric as far as I can tell, which can make it hard to find what you want in a very large database with many periods and ledgers.

**Comment by patrickzurek** [comment]
Hmm, you can disregard my question about them being in sync.  I was thinking of something else when I asked that.

Pat

**Comment by patrickzurek** [comment]
I applied ORDER BY in the SQL so they became:

SELECT LEDGER.LEDGER_NAME
FROM LEDGER ORDER BY LEDGER_NAME;

and

SELECT FISCAL_PERIOD.FISCAL_PERIOD_NAME
FROM FISCAL_PERIOD ORDER BY FISCAL_PERIOD_NAME;

How does it look now?

**Comment by gibsonjc** [comment]
Yes, adding ORDER BY is MUCH better!  I think this one is done unless you have anything else.
