### ISSUE TITLE
Pending reports should time-out

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#37]
I ran the report BIB RECORDS CREATED BY OPERATOR but instead of entering dates in the parameters boxes, I input letters.  I think the invalid parameters caused the report to get stuck in the Pending stage:

BIB RECORDS CREATED BY OPERATOR (Pending)       Pending         Apr. 04, 2016, 01:04 PM         62194755

Reports that are Pending for a long time should time-out or produce an error or something so the user knows what is going on.

Are Pending reports using any system resources?  Or is it just that the display doesn't get updated with anything useful?

**Comment by patrickzurek** [comment]
Pending reports that have failed to complete because of an error aren't using any resources.  I've added code that removes pending reports older than 24 hours from the database on devel.  I'm going to close this issue now without giving Jessica the opportunity to test and if a report gets stuck in the pending state again and its noticed that it has stuck around for more than a day, then the issue can be re-opened.
