### ISSUE TITLE
Adjust the Results list configurations

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#46]
At today's meeting we decided to:

Set the Results list to have no length limit.  
Set the length of time to keep report results to be 7 days.

These are updates to issue #17

**Comment by patrickzurek** [comment]
Changes to the code have been made on devel.  The length of the results list is configured in the settings file by the parameter MAX_RESULTS_TO_SHOW and it's set to -1 where -1 indicates no limit, otherwise a positive number indicates max number of reports to show.  Length of time to keep report results is set to 7 days configured by the parameter MAX_AGE_OF_REPORT = 7.

**Comment by patrickzurek** [comment]
This has been pushed to production.
