### ISSUE TITLE
Enable CSV output of report data

### ISSUE THREAD

**Issue by patrickzurek** [CARLI/web-reports#6]
(n/t)

**Comment by gibsonjc** [comment]
In #34 you said you enabled CSV on devel.  Since this is the CSV issue I thought I should comment this here: 

When I click the CSV file to download on web-reports-devel, the file downloads but it does not have a .csv extension by default.  The filename is the id and then what looks like a random string with no file extension: 7644a446-937c-4a22-9067-2a4e8ee824d7

**Comment by patrickzurek** [comment]
D'oh.  It was working when I commented on the issue but then I moved a few lines of code around and broke the filename from working right.  I fixed it.

**Comment by gibsonjc** [comment]
Thanks!  CSV output seems to be working properly as far as I can tell.  The filenames have a useful name, and I've successfully opened several in Excel.
