### ISSUE TITLE
count of the number of records in a record set on Results page

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#78]
Would it be possible to include a column for the number of records in a record set in the list on the Results page?

**Comment by patrickzurek** [comment]
This is in on devel.  Let me know what you think about how it looks positioned in the table between Parameters and Created.  Or if the wording of "Row Count" should be changed.  When testing, don't forget that the row count in the csv file will be off by one at the bottom because of the addition of line #1 which lists the column names.

**Comment by gibsonjc** [comment]
Looks great to me. Onwards to prod!

**Comment by patrickzurek** [comment]
Pushed to prod.
