### ISSUE TITLE
Report "UB Stat 4b - Details by Pickup Location" gives datatables warning

### ISSUE THREAD

**Issue by gibsonjc** [CARLI/web-reports#84]
Running UB Stat 4b - Details by Pickup Location for KNXdb on web-reports-devel gives this error:
![screen shot 2016-06-15 at 10 36 47 am](https://cloud.githubusercontent.com/assets/17598357/16086453/344aaa40-32e5-11e6-8160-29cc401a5414.png)
I can click OK and then see the results, but obviously this message is no good.

universal_borrowing => ubstat4b_details_by_pickup_location.report

**Comment by gibsonjc** [comment]
Web Reports results do match Access results.

**Comment by patrickzurek** [comment]
This one wasn't working because there was an additional blank column field in the report template added in the admin interface:

<img width="694" alt="screen shot 2016-06-17 at 1 30 58 pm" src="https://cloud.githubusercontent.com/assets/6615138/16160837/e8dd092a-348f-11e6-8363-98ba7b2fb529.png">

There will cause datatables to throw and error because it's expecting an extra row that doesn't exist.  Remember not to leave stray empty fields around (use the - to remove them).

**Comment by gibsonjc** [comment]
Looks good, ready for prod.

**Comment by patrickzurek** [comment]
Pushed to prod
