### ISSUE TITLE
More newly entered reports

### ISSUE THREAD

**Issue by csaundrs** [CARLI/web-reports#94]
If these check out ok, they are ready for production:  ( I found that one  of them, designated by *\* does not work, but the rest return either results or zero rows)
- Bib record 035 $a contains (XXXdb)nnnn   (Local Cat Maint > Bibliographic Records: Control Numbers)
- Bib record without UT but title contains transl   (Local Cat Maint > Bibliographic Records: Titles)
- Bib record without UT but 700 field contains tr   (Local Cat Maint > Bibliographic Records: Titles)
- Bib record without UT but 6xx field contains Translations into (Local Cat Maint > Bibliographic Records: Titles)
- *\* Unindexed Call Numbers   (Local Cat Maint > MFHD Records: Call Numbers)
  *\* This one seems not to be working.  Likely because we are specifically searching for a $ in the SQL query and it is probably being interpreted as if it is a variable.
- Serial bib records without an ISSN      (Local Cat Maint > Bibliographic Records: Control Numbers)
- Find 020's with multiple $'s   (Local Cat Maint > Bibliographic Records: Control Numbers)
- Bib records with an ISSN but format is not for serials    (Local Cat Maint > Bibliographic Records: Control Numbers)

**Comment by gibsonjc** [comment]
- Bib record 035 $a contains (XXXdb)nnnn   (Local Cat Maint > Bibliographic Records: Control Numbers) 
  --DUPLICATE .  I deleted this one via the admin interface because this report was already present since June 29.
- Bib record without UT but title contains transl   (Local Cat Maint > Bibliographic Records: Titles) 
- Bib record without UT but 700 field contains tr (Local Cat Maint > Bibliographic Records: Titles)
- Bib record without UT but 6xx field contains Translations into (Local Cat Maint > Bibliographic Records: Titles)
  --These three similar reports all work and return the same results as Access, however, one of them (Bib record without UT but title contains transl) prompts for starting and ending bib number while the other two do not, and the other two appear to have hardcoded numbers of **WHERE ((BIB_TEXT.BIB_ID Between 300  AND  3000000** in the SQL.  I'm not sure why these queries on our Shared SQL page had prompts for beginning and ending bibs anyway.  Can you rewrite all three of these to find all matching records without prompting for start and end bib IDs?
- *\* Unindexed Call Numbers   (Local Cat Maint > MFHD Records: Call Numbers)
  *\* This one seems not to be working.  Likely because we are specifically searching for a $ in the SQL query and it is probably being interpreted as if it is a variable.
  --This report is working fine for me and returns the same results as Access in KNXdb on devel. Where is it not running for you?
- Serial bib records without an ISSN      (Local Cat Maint > Bibliographic Records: Control Numbers)
  --In KNXdb on devel, web-reports is returning zero results, but in Access this query returns 1873 results.
- Find 020's with multiple $'s   (Local Cat Maint > Bibliographic Records: Control Numbers)
  --In KNXdb on devel, web-reports is returning zero results, but in Access this query returns 2924 results.
- Bib records with an ISSN but format is not for serials    (Local Cat Maint > Bibliographic Records: Control Numbers)
  --This one looks good; results match Access!

**Comment by csaundrs** [comment]
On the 3 that have bib_id ranges, should I take out that condition altogether or should I hard code the upper and lower limits to certain values?

**Comment by gibsonjc** [comment]
Since we have databases of varying sizes, I think it would be simplest if you can take out the condition altogether so that any library running this report will find all of the matching bibs in their entire database.  Unless you see something that makes this a bad idea for performance or unreasonable results times, of course!

**Comment by patrickzurek** [comment]
> Serial bib records without an ISSN (Local Cat Maint > Bibliographic Records: Control Numbers)
> --In KNXdb on devel, web-reports is returning zero results, but in Access this query returns 1873 results.

There were two problems with the way this report was entered.  The first was easy to fix.  BIB_TEXT did not belong before the column names and also the alias (or whatever it's called in Oracle world) for "SUBSTR(FIELD_008,7,1)" Publication Status should have been entered instead:

<img width="753" alt="screen shot 2016-08-23 at 2 24 12 pm" src="https://cloud.githubusercontent.com/assets/6615138/17904454/6a00134e-693d-11e6-9420-1f99fd08edea.png">

<img width="765" alt="screen shot 2016-08-23 at 2 21 54 pm" src="https://cloud.githubusercontent.com/assets/6615138/17904468/74b34ac2-693d-11e6-8a80-5881882b2815.png">

About the second problem: some googling revealed that Oracle treats empty strings as null.  So I replaced ' ' with null.  Now it returns 1873 rows in web-reports, same as @gibsonjc reported in Access.

**Comment by patrickzurek** [comment]
I'm troubleshooting

> Find 020's with multiple $'s (Local Cat Maint > Bibliographic Records: Control Numbers)
> --In KNXdb on devel, web-reports is returning zero results, but in Access this query returns 2924 results.

Jessica,
Can you please post some matches for this query from Access or (preferably) email me the Access file if it's not too large (if needed you can right click on the file in macOS and click compress...).  That would be a great help.

Thanks.

**Comment by patrickzurek** [comment]
This is about "Find 020's with multiple $'s (Local Cat Maint > Bibliographic Records: Control Numbers)."

Chris, did you craft the regexp yourself used in the query or did you get it from somewhere else?  I'm no expert on regular expressions by any means but I think I see a few problems with it (for one, I don't think the use of anchors belongs?).  Unfortunately, my attempt suffers from a problem too.  With my mine I get 2,925 results compared to Jessica's 2,924.  I used `([0-9]{9}).*{2,}`  I don't think this one is truly correct since it will only match on double ISBNs, not entries with 3 or more.

**Comment by patrickzurek** [comment]
Oops, I copy pasted the wrong regexp that I used.  I meant to paste.  `'([0-9]{9}).*([0-9]{9})')`

**Comment by patrickzurek** [comment]
I'm making typos left and right.  In my last post I left an errant parenthesis on the right end of the string that shouldn't have been there.  

Anyway, I think I may have come up with one that should match 2 or more ISBNs:  `([0-9]{9}).*([0-9]{9}).*{1,}`

It still returns the same amount for KNX: 2,925, but Jessica, could that be because there simply aren't any 020 fields that contain more than 2 ISBNs in KNXdb?  I ran the query on UIU and found some results like:

8470900315 (set) 8470900323 (v.1) 847090048X (v.2)
3487041766 (v.1) 3487041774 (v.2) 3487041782 (v.3)

**Comment by gibsonjc** [comment]
Just sent you the KNXdb on devel Access output via email (Excel spreadsheet).

KNXdb does have bibs with more than two 020 $a's like this one that can be found in both the Access and the web-reports output:
BIB ID 1689
0873952855 0873952863 (pbk.) 0873952871 (micro.)

**Comment by patrickzurek** [comment]
> KNXdb does have bibs with more than two 020 $a's like this one that can be found in both the Access and the web-reports output:

I was confused why my first regex that I posted would return bibs with more than two ISBNs when I expected it to match two and only two ISBNs.  But I made a really dumb mistake in my regexp: "`.*`"

The error is obviously present in`([0-9]{9}).*([0-9]{9}).*{1,}` too.

I'll work on refining it further.

**Comment by gibsonjc** [comment]
Closing. Split apart into 102, 103, and 104.
